/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TooltipRouteImport } from './routes/tooltip'
import { Route as SwitchRouteImport } from './routes/switch'
import { Route as SliderRouteImport } from './routes/slider'
import { Route as SelectRouteImport } from './routes/select'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as LabelRouteImport } from './routes/label'
import { Route as InputRouteImport } from './routes/input'
import { Route as DialogRouteImport } from './routes/dialog'
import { Route as CheckboxRouteImport } from './routes/checkbox'
import { Route as ButtonRouteImport } from './routes/button'
import { Route as IndexRouteImport } from './routes/index'

const TooltipRoute = TooltipRouteImport.update({
  id: '/tooltip',
  path: '/tooltip',
  getParentRoute: () => rootRouteImport,
} as any)
const SwitchRoute = SwitchRouteImport.update({
  id: '/switch',
  path: '/switch',
  getParentRoute: () => rootRouteImport,
} as any)
const SliderRoute = SliderRouteImport.update({
  id: '/slider',
  path: '/slider',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelRoute = LabelRouteImport.update({
  id: '/label',
  path: '/label',
  getParentRoute: () => rootRouteImport,
} as any)
const InputRoute = InputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogRoute = DialogRouteImport.update({
  id: '/dialog',
  path: '/dialog',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckboxRoute = CheckboxRouteImport.update({
  id: '/checkbox',
  path: '/checkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonRoute = ButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/button': typeof ButtonRoute
  '/checkbox': typeof CheckboxRoute
  '/dialog': typeof DialogRoute
  '/input': typeof InputRoute
  '/label': typeof LabelRoute
  '/radio': typeof RadioRoute
  '/select': typeof SelectRoute
  '/slider': typeof SliderRoute
  '/switch': typeof SwitchRoute
  '/tooltip': typeof TooltipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/button': typeof ButtonRoute
  '/checkbox': typeof CheckboxRoute
  '/dialog': typeof DialogRoute
  '/input': typeof InputRoute
  '/label': typeof LabelRoute
  '/radio': typeof RadioRoute
  '/select': typeof SelectRoute
  '/slider': typeof SliderRoute
  '/switch': typeof SwitchRoute
  '/tooltip': typeof TooltipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/button': typeof ButtonRoute
  '/checkbox': typeof CheckboxRoute
  '/dialog': typeof DialogRoute
  '/input': typeof InputRoute
  '/label': typeof LabelRoute
  '/radio': typeof RadioRoute
  '/select': typeof SelectRoute
  '/slider': typeof SliderRoute
  '/switch': typeof SwitchRoute
  '/tooltip': typeof TooltipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/button'
    | '/checkbox'
    | '/dialog'
    | '/input'
    | '/label'
    | '/radio'
    | '/select'
    | '/slider'
    | '/switch'
    | '/tooltip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/button'
    | '/checkbox'
    | '/dialog'
    | '/input'
    | '/label'
    | '/radio'
    | '/select'
    | '/slider'
    | '/switch'
    | '/tooltip'
  id:
    | '__root__'
    | '/'
    | '/button'
    | '/checkbox'
    | '/dialog'
    | '/input'
    | '/label'
    | '/radio'
    | '/select'
    | '/slider'
    | '/switch'
    | '/tooltip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ButtonRoute: typeof ButtonRoute
  CheckboxRoute: typeof CheckboxRoute
  DialogRoute: typeof DialogRoute
  InputRoute: typeof InputRoute
  LabelRoute: typeof LabelRoute
  RadioRoute: typeof RadioRoute
  SelectRoute: typeof SelectRoute
  SliderRoute: typeof SliderRoute
  SwitchRoute: typeof SwitchRoute
  TooltipRoute: typeof TooltipRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/tooltip': {
      id: '/tooltip'
      path: '/tooltip'
      fullPath: '/tooltip'
      preLoaderRoute: typeof TooltipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/switch': {
      id: '/switch'
      path: '/switch'
      fullPath: '/switch'
      preLoaderRoute: typeof SwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slider': {
      id: '/slider'
      path: '/slider'
      fullPath: '/slider'
      preLoaderRoute: typeof SliderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/label': {
      id: '/label'
      path: '/label'
      fullPath: '/label'
      preLoaderRoute: typeof LabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/input': {
      id: '/input'
      path: '/input'
      fullPath: '/input'
      preLoaderRoute: typeof InputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog': {
      id: '/dialog'
      path: '/dialog'
      fullPath: '/dialog'
      preLoaderRoute: typeof DialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkbox': {
      id: '/checkbox'
      path: '/checkbox'
      fullPath: '/checkbox'
      preLoaderRoute: typeof CheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button': {
      id: '/button'
      path: '/button'
      fullPath: '/button'
      preLoaderRoute: typeof ButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ButtonRoute: ButtonRoute,
  CheckboxRoute: CheckboxRoute,
  DialogRoute: DialogRoute,
  InputRoute: InputRoute,
  LabelRoute: LabelRoute,
  RadioRoute: RadioRoute,
  SelectRoute: SelectRoute,
  SliderRoute: SliderRoute,
  SwitchRoute: SwitchRoute,
  TooltipRoute: TooltipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
