/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as AdminIndexRouteImport } from './routes/admin/index'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/consent': typeof ConsentRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/consent': typeof ConsentRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/consent': typeof ConsentRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/consent' | '/profile' | '/sign-in' | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/consent' | '/profile' | '/sign-in' | '/admin'
  id: '__root__' | '/consent' | '/profile' | '/sign-in' | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConsentRoute: typeof ConsentRoute
  ProfileRoute: typeof ProfileRoute
  SignInRoute: typeof SignInRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ConsentRoute: ConsentRoute,
  ProfileRoute: ProfileRoute,
  SignInRoute: SignInRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
