/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticated_rootRouteImport } from './routes/(authenticated)/__root'
import { Route as authenticatedAdmin_rootRouteImport } from './routes/(authenticated)/admin/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authenticatedProfileRouteImport } from './routes/(authenticated)/profile'
import { Route as authenticatedDashboardRouteImport } from './routes/(authenticated)/dashboard'
import { Route as authenticatedAdminIndexRouteImport } from './routes/(authenticated)/admin/index'
import { Route as authenticatedAdminUsersRouteImport } from './routes/(authenticated)/admin/users'
import { Route as authenticatedAdminPermissionsRouteImport } from './routes/(authenticated)/admin/permissions'
import { Route as authenticatedAdminAuditLogsRouteImport } from './routes/(authenticated)/admin/audit-logs'

const authenticated_rootRoute = authenticated_rootRouteImport.update({
  id: '/(authenticated)/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedAdmin_rootRoute = authenticatedAdmin_rootRouteImport.update({
  id: '/(authenticated)/admin/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedProfileRoute = authenticatedProfileRouteImport.update({
  id: '/(authenticated)/profile',
  path: '/profile',
  getParentRoute: () => authenticated_rootRoute,
} as any)
const authenticatedDashboardRoute = authenticatedDashboardRouteImport.update({
  id: '/(authenticated)/dashboard',
  path: '/dashboard',
  getParentRoute: () => authenticated_rootRoute,
} as any)
const authenticatedAdminIndexRoute = authenticatedAdminIndexRouteImport.update({
  id: '/(authenticated)/admin/',
  path: '/admin/',
  getParentRoute: () => authenticated_rootRoute,
} as any)
const authenticatedAdminUsersRoute = authenticatedAdminUsersRouteImport.update({
  id: '/(authenticated)/admin/users',
  path: '/admin/users',
  getParentRoute: () => authenticated_rootRoute,
} as any)
const authenticatedAdminPermissionsRoute =
  authenticatedAdminPermissionsRouteImport.update({
    id: '/(authenticated)/admin/permissions',
    path: '/admin/permissions',
    getParentRoute: () => authenticated_rootRoute,
  } as any)
const authenticatedAdminAuditLogsRoute =
  authenticatedAdminAuditLogsRouteImport.update({
    id: '/(authenticated)/admin/audit-logs',
    path: '/admin/audit-logs',
    getParentRoute: () => authenticated_rootRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof authenticatedDashboardRoute
  '/profile': typeof authenticatedProfileRoute
  '/admin': typeof authenticatedAdmin_rootRoute
  '/admin/audit-logs': typeof authenticatedAdminAuditLogsRoute
  '/admin/permissions': typeof authenticatedAdminPermissionsRoute
  '/admin/users': typeof authenticatedAdminUsersRoute
  '/admin/': typeof authenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof authenticatedDashboardRoute
  '/profile': typeof authenticatedProfileRoute
  '/admin': typeof authenticatedAdminIndexRoute
  '/admin/audit-logs': typeof authenticatedAdminAuditLogsRoute
  '/admin/permissions': typeof authenticatedAdminPermissionsRoute
  '/admin/users': typeof authenticatedAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/(authenticated)/__root': typeof authenticated_rootRoute
  '/(authenticated)/dashboard': typeof authenticatedDashboardRoute
  '/(authenticated)/profile': typeof authenticatedProfileRoute
  '/(authenticated)/admin/__root': typeof authenticatedAdmin_rootRoute
  '/(authenticated)/admin/audit-logs': typeof authenticatedAdminAuditLogsRoute
  '/(authenticated)/admin/permissions': typeof authenticatedAdminPermissionsRoute
  '/(authenticated)/admin/users': typeof authenticatedAdminUsersRoute
  '/(authenticated)/admin/': typeof authenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/profile'
    | '/admin'
    | '/admin/audit-logs'
    | '/admin/permissions'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/profile'
    | '/admin'
    | '/admin/audit-logs'
    | '/admin/permissions'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/(authenticated)/__root'
    | '/(authenticated)/dashboard'
    | '/(authenticated)/profile'
    | '/(authenticated)/admin/__root'
    | '/(authenticated)/admin/audit-logs'
    | '/(authenticated)/admin/permissions'
    | '/(authenticated)/admin/users'
    | '/(authenticated)/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  authenticated_rootRoute: typeof authenticated_rootRoute
  authenticatedDashboardRoute: typeof authenticatedDashboardRoute
  authenticatedProfileRoute: typeof authenticatedProfileRoute
  authenticatedAdmin_rootRoute: typeof authenticatedAdmin_rootRoute
  authenticatedAdminAuditLogsRoute: typeof authenticatedAdminAuditLogsRoute
  authenticatedAdminPermissionsRoute: typeof authenticatedAdminPermissionsRoute
  authenticatedAdminUsersRoute: typeof authenticatedAdminUsersRoute
  authenticatedAdminIndexRoute: typeof authenticatedAdminIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/(authenticated)/__root': {
      id: '/(authenticated)/__root'
      path: '/'
      fullPath: ''
      preLoaderRoute: typeof authenticated_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/admin/__root': {
      id: '/(authenticated)/admin/__root'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof authenticatedAdmin_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/profile': {
      id: '/(authenticated)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authenticatedProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/admin/': {
      id: '/(authenticated)/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof authenticatedAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/admin/users': {
      id: '/(authenticated)/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof authenticatedAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/admin/permissions': {
      id: '/(authenticated)/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof authenticatedAdminPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/admin/audit-logs': {
      id: '/(authenticated)/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof authenticatedAdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  authenticated_rootRoute: authenticated_rootRoute,
  authenticatedDashboardRoute: authenticatedDashboardRoute,
  authenticatedProfileRoute: authenticatedProfileRoute,
  authenticatedAdmin_rootRoute: authenticatedAdmin_rootRoute,
  authenticatedAdminAuditLogsRoute: authenticatedAdminAuditLogsRoute,
  authenticatedAdminPermissionsRoute: authenticatedAdminPermissionsRoute,
  authenticatedAdminUsersRoute: authenticatedAdminUsersRoute,
  authenticatedAdminIndexRoute: authenticatedAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
declare module '@tanstack/solid-router' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
